# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bellatrix Docs
email: aangelov@bellatrix.solutions
description: >- # this means to ignore newlines until "baseurl:"
  Here you can find rich documentation about the different features and configurations of Bellatrix Test Framework.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.bellatrix.solutions" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll
permalink: /:title/
#source: jekyll
#destination: documentation 
# Build settings
markdown: kramdown
# theme: minima
plugins:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
navigation: 
    "overview":
        title: Overview
    "system-requirements":
        title: System Requirements
    "installation":
        title: Installation
    "activation":
        title: Activation
    "how-to-use-starter-kits":
        title: How to Use Starter Kits?
    "control-browser":
        title: Control Browser
    "navigate-to-pages":
        title: Navigate to Pages
    "locate-elements":
        title: Locate Elements
    "locate-and-wait-elements":
        title: Locate and Wait Elements
    "wait-for-elements":
        title: Wait for Elements
    "browser-service":
        title: BrowserService
    "dialog-service":
        title: DialogService
    "cookies-service":
        title: CookiesService
    "javascript-service":
        title: JavaScriptService
    "common-controls":
        title: Common Controls
    "normal-assertions":
        title: Normal Assertions
    "ensure-assertions":
        title: Ensure Assertions
    "bdd-logging":
        title: BDD Logging
    "page-objects":
        title: Page Objects
    "layout-testing":
        title: Layout Testing
    "layout-testing":
        title: Layout Testing
    "troubleshooting-full-page-screenshots-on-fail":
        title: Troubleshooting- Full Page Screenshots on Fail
    "troubleshooting-video-recording":
        title: Troubleshooting- Video Recording
    "troubleshooting-failed-tests-analysis":
        title: Troubleshooting- Failed Tests Analysis
    "elements-snippets":
        title: Elements Snippets
    "capture-http-traffic":
        title: Capture HTTP Traffic
    "execute-tests-selenium-grid":
        title: Execute Tests in Selenium Grid
    "execute-tests-saucelabs":
        title: Execute Tests in SauceLabs
    "execute-tests-browserstack":
        title: Execute Tests in BrowserStack
    "execute-tests-crossbrowsertesting":
        title: Execute Tests in CrossBrowserTesting
    "add-custom-webdriver-capabilities-options":
        title: Add Custom WebDriver Capabilities and Options
    "static-analysis":
        title: Static Analysis
    "logging":
        title: Logging
    "extensability-test-workflow-hooks":
        title: Extensability- Test Workflow Hooks
    "extensability-custom-test-workflow-plugins":
        title: Extensability- Custom Test Workflow Plugins
    "extensability-override-globally-element-actions":
        title: Extensability- Override Globally Element Actions
    "extensability-override-locally-element-actions":
        title: Extensability- Override Locally Element Actions
    "extensability-element-action-hooks":
        title: Extensability- Element Action Hooks
    "extensability-common-services-action-hooks":
        title: Extensability- Common Services Action Hooks
    "extensability-extend-existing-elements-extension-methods":
        title: Extensability- Extend Elements Extension Methods
    "extensability-extend-existing-elements-child-elements":
        title: Extensability- Extend Elements Child Elements
    "extensability-extend-common-services":
        title: Extensability- Extend Common Services
    "templates":
        title: Templates
    "folder-and-file-structure":
        title: Folder and File Structure
        
        